Don't shadow the binary

diff --git a/setgov b/setgov
--- a/setgov
+++ b/setgov
@@ -14,7 +14,7 @@ EOF
 
 	exit 1
 }
-setgov()
+set_governor()
 {
 	for gov in /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor; do
 		echo "$1" > "$gov" || return 1
@@ -32,5 +32,5 @@ while [ "$1" ]; do
 done
 [ "$1" ] || die
 
-setgov "$1" || die "Unable to set scaling governor"
+set_governor "$1" || die "Unable to set scaling governor"
 # [ "$1"  = "performance" ] && /usr/local/sbin/zenstates --c6-enable
